version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current

jobs:
  deploy:
    parameters:
      env:
        type: string
        default: production
    executor: base
    steps:
      - checkout
      - run:
          name: Download Platform appcli
          command: curl -sS -L https://platform.algolia.net/public/install.sh | bash
      - run:
          name: Deploy to Platform
          command: appcli environment deploy

workflows:
  deploy:
    jobs:
      - deploy:
          name: deploy-production
          filters:
            branches:
              only:
                - main
      - deploy:
          name: deploy-testing
          env: testing
          filters:
            branches:
              only:
                - welcome-to-api
